version: "2"

volumes:
  nexus-data: {}
  jenkins-data: {}

services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./home:/home
      - /var/run/docker.sock:/var/run/docker.sock

  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
